name: Codacy Coverage
on: [push, pull_request]

jobs:
  report-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests with coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=my_project --cov-report=xml

      - name: Upload to Codacy
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
